name = "YYZRecipes"
uuid = "fea72d09-395e-499c-bda5-4cbe184b4e61"
authors = ["yiyuezhuo <yiyuezhuo@gmail.com> and contributors"]
version = "0.1.0"

[deps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
RecipesBase = "1.0"
Requires = "1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
